# -*- coding: utf-8 -*-
"""DC_Exp6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sr_qLZnJ7IkjbMNY4vG7k1uWfKNF5vAM
"""

import numpy as np
import matplotlib.pyplot as plt

data=np.array([1,0,1,0,1,0,1,1])
data

data=np.hstack((data,[0]))
data

bitrate=1
T=len(data)/bitrate
n=500
N=n*len(data)#No of time Samples

u_nrz=np.zeros((N,1))
u_rz=np.zeros((N,1))
p_nrz=np.zeros((N,1))
p_rz=np.zeros((N,1))
dt=T/N
t=np.arange(0,T,dt)

#Unipolar NRZ
for i in range(len(data)-1):
  if data[i]==1:
    u_nrz[i*n+1:(i+1)*n+1]=1
  else:
    u_nrz[i*n+1:(i+1)*n+1]=0
plt.plot(t,u_nrz)

#Polar NRZ
for i in range(len(data)-1):
  if data[i]==1:
    p_nrz[i*n+1:(i+1)*n+1]=1
  else:
    p_nrz[i*n+1:(i+1)*n+1]=-1
plt.plot(t,p_nrz)

#Unipolar RZ
for i in range(len(data)-1):
  if data[i]==1:
    u_rz[int(i*n+1):int((i+0.5)*n)]=1
    u_rz[int((i+0.5)*n+1):int((i+1)*n+1)]=0
  else:
    u_rz[int(i*n+1):int((i+1)*n+1)]=0
plt.plot(t,u_rz)

#Polar RZ
for i in range(len(data)-1):
  if data[i]==1:
    p_rz[int(i*n+1):int((i+0.5)*n)]=1
    p_rz[int((i+0.5)*n+1):int((i+1)*n+1)]=0
  else:
    p_rz[int(i*n+1):int((i+0.5)*n)]=-1
    p_rz[int((i+0.5)*n+1):int((i+1)*n+1)]=0
plt.plot(t,p_rz)