# -*- coding: utf-8 -*-
"""DC_Exp7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vUncwM30zAJkklFPNYhEb_TQeu_dm4Y2
"""

import numpy as np
from math import pi
import matplotlib.pyplot as plt

fL=2
fH=4
data=np.array([1,0,1,0,1])
print("Data : ",data)

t=np.arange(0,1,1/500)
xL=np.sin(2*pi*fL*t)
xH=np.sin(2*pi*fH*t)

fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(10,10))

# counter to increment the time
z = 0

# converting (0,1) to (-1,1)
data_psk = 2*data - 1

lw = 3 # linewidth
fs = 18 # fontsize

for i in range(len(data)):
  # Carrier signal
  ax1.plot(t+z, xL, linewidth = lw)
  ax1.set_ylabel('Carrier signal', fontsize = fs)
  ax1.grid()

  # ASK signal
  ax2.plot(t+z, xL * data[i], linewidth = lw)
  ax2.set_ylabel('ASK signal', fontsize = fs)
  ax2.grid()

  # PSK signal
  ax3.plot(t+z, xL * data_psk[i], linewidth = lw)
  ax3.set_ylabel('PSK signal', fontsize = fs)
  ax3.grid()

  # FSK signal
  if data[i] == 0:
    ax4.plot(t+z, xL, linewidth = lw)
  else:
    ax4.plot(t+z, xH, linewidth = lw)
  ax4.set_ylabel('FSK signal', fontsize = fs)
  ax4.grid()
  z = z + 1 # increment the counter