# -*- coding: utf-8 -*-
"""DC_Exp2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sz-zIcHVc9QC-iFLuKBd4H2nmt-ELXW3
"""

import numpy as np
n=7
k=4
P=np.array([[0,1,1],[1,1,1],[1,1,0],[1,0,1]])
P

I=np.eye(k)
I

G=np.hstack((I,P))
G

m=np.arange(2**k)
m

D=np.zeros((2**k,k))
D

for i in m:
  z='{0:04b}'.format(i)
  zs=[int(j) for j in z]
  D[i,:]=zs
D

C=np.dot(D,G)
print("Codeword\n",C)

C=C%2
print(C)

C=C.astype(int)
print(C)

#Decoding
idx=12
loc=3
R=C[idx,:]
R

R[loc]=int(not R[loc])
R

J=np.eye(n-k)
J

H=np.hstack((P.T,J))
H

S=np.dot(R,H.T)
S

S=S%2
S

X=H.T
X

for n in range(X.shape[0]):
  if np.array_equal(S,X[n,:]):
    R[n]=int(not R[n])
    print("Error in bit : ",n)
    break
print("Corrected codeword : ",R)