# -*- coding: utf-8 -*-
"""DC_Exp4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPMbMk5ADJs379tpGK0snBtnJycY-BRb

Name : Ojas Kambli Roll no. : 47 Semester : V Branch : EXTC Year of Study : TE (Third Year) Division : TE A Batch : A3

Finding convolution code using Frequency Domain
"""

import numpy as np
v1=np.array([1,1,0])
v1p=np.poly1d(v1)
print("V1= ",v1,"\n V1 polynomial :\n",v1p)

v2=np.array([1,1,1])
v2p=np.poly1d(v2)
print("V2= ",v2,"\n V2 polynomial :\n",v2p)

m=np.array([1,0,0,1,0,0,1,1])
mp=np.poly1d(m)
print("M= ",m,"\n Message polynomial :\n",mp)

V1=v1p*mp
print(" The V1 solution polynomial :\n",V1)

V2=v2p*mp
print(" The V2 solution polynomial :\n",V2)

V1s=(V1.c)%2
print("The V1 solution in binary :\n",V1s)

V2s=(V2.c)%2
print("The V2 solution in binary :\n",V2s)

C=np.zeros((V1s.shape[0],2))
for i in range(V1s.shape[0]):
  C[i,:]=[V1s[i],V2s[i]]
print("The codeword is :",(C.flatten()))

"""Finding convolution code using Frequency Domain"""

v1s=(np.convolve(v1,m))%2
print("V1 in binary is :",v1s)

v2s=(np.convolve(v2,m))%2
print("V2 in binary is :",v2s)

CW=np.zeros((v1s.shape[0],2))
for i in range(v1s.shape[0]):
  CW[i,:]=[v1s[i],v2s[i]]
print("The codeword is :",(CW.flatten()))