# -*- coding: utf-8 -*-
"""DC_Exp3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VrLLVTFvsqebVUwyeypIbOs5VOu1_Bxv
"""

import numpy as np
G=np.array([1,0,1,1])
M=np.array([1,0,0,1])
g=np.poly1d(G)
m=np.poly1d(M)
print("Generator polynomial :\n",g)
print("Message polynomial :\n",m)

r=g.order
parity=np.zeros((r+1))
parity[0]=1
Parity=np.poly1d(parity)
print("The parity polynomial is :\n",Parity)

m_shifted=np.polymul(m,Parity)
print("The shifted message polynomial is :\n",m_shifted)

q,rem=np.polydiv(m_shifted,g)
print(rem)

R=rem.c
R=R%2
print("The remainder matrix is :\n",R)

C=np.hstack((M,R))
C=C.astype(int)
print("The codeword is :\n",C)

#Decoding
RC=C
RC[3]=int(not RC[3])
print("The received codeword is :\n",RC)

rc=np.poly1d(RC)
print("The received message polynomial is :\n",rc)

q,s=np.polydiv(rc,g)
print("Remainder polynomial is :\n",s)

S=s.c
S=S%2
print("The syndrome is :\n",S)

if S.all==0:
  print("No error")
else:
  print("Error")